---
- name: install nginx
  hosts: all
  gather_facts: yes
  tasks: 
    - name: apt update
      apt: 
        name: apt 
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install nginx to ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"


    - name: epel-repo for CentOS
      yum: 
        name: epel-release
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install nginx CentOS
      yum: 
        name: nginx
        state: latest
      when: ansible_distribution == "CentOS"    

    - name: start service nginx, if it's not started
      systemd:
        name: nginx
        state: started
        enabled: yes